create table subasta (
    id                   uuid                     primary key,
    version              bigint                   not null,
    nombre               varchar(120)             not null,
    descripcion          varchar(1000),
    fecha_inicio         timestamp with time zone not null,
    estado               varchar(20)              not null,
    subastador_id        uuid                     not null,
    subastador_nombre    varchar(50)              not null,

    -- Ficha técnica del lote (HU-09)
    ficha_identificacion varchar(100),
    ficha_raza           varchar(100),
    ficha_peso_kg        numeric(10, 2),
    ficha_edad_meses     integer,
    ficha_observaciones  varchar(1000),

    -- Reglas de puja (HU-10); reglas_version sube cada vez que se reconfiguran
    duracion_minutos     integer,
    precio_base          bigint,
    incremento_minimo    bigint,
    reglas_version       integer                  not null default 0,

    -- Estado en curso (HU-12, HU-13, HU-14)
    hora_inicio          timestamp with time zone,
    hora_fin             timestamp with time zone,
    precio_actual        bigint,
    lider_id             uuid,
    lider_nombre         varchar(50),
    cantidad_pujas       integer                  not null default 0,

    creada_en            timestamp with time zone not null
);

create index ix_subasta_estado_fecha on subasta (estado, fecha_inicio);
create index ix_subasta_subastador   on subasta (subastador_id, fecha_inicio);

-- Solo las pujas aceptadas quedan registradas (HU-14).
create table puja (
    id             uuid                     primary key,
    subasta_id     uuid                     not null references subasta (id),
    usuario_id     uuid                     not null,
    usuario_nombre varchar(50)              not null,
    monto          bigint                   not null,
    creada_en      timestamp with time zone not null
);

create index ix_puja_subasta_monto on puja (subasta_id, monto);

-- Outbox transaccional: el evento se guarda en la misma transacción que el cambio de estado
-- y un publicador lo envía luego al broker.
create table outbox (
    id           bigint generated by default as identity primary key,
    event_id     uuid                     not null,
    tipo         varchar(60)              not null,
    payload      text                     not null,
    creado_en    timestamp with time zone not null,
    publicado_en timestamp with time zone
);

create index ix_outbox_pendientes on outbox (publicado_en, id);
